version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/backend/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/backend/seed_data"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
